#!/bin/bash
git add .
if [[ $1 ]] 
then
git commit -m "$1"
else
git commit -m "updates"
fi
git push
i=0
while [ $i -lt 80 ]
do
echo -ne "$(tput setaf 2)="
i=$[$i+1]
done
DATE=$(date +"%D %T")
echo "Committed to Waverly Project on $DATE"
while [ $i -gt 0 ]
do
sleep 0.1
echo -ne "="
i=$[$i-1]
done
open http://fdch.github.io/wp
echo "$(tput sgr 0)"
exit
